[package]
name = "kem_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
libaes = "0.6.4"
base2048 = "2.0.2"
pqc_kyber = {version = "0.3.0", features = ["kyber1024"]}